version: '2'
services:
   identidock:
      build: .
      ports:
         - "5000:5000"
      volumes:
         - "./app:/app"
      environment:
         ENV: DEV
      links:
         - dnmonster
         - redis
   
   dnmonster:
      image: amouat/dnmonster:1.0
   
   redis:
      image: redis:3.0
