version: '2'
services:
   identidock:
      build: .
      ports:
         - "5000:5000"
      volumes:
         - "./app:/app"
      environment:
         ENV: DEV
      links:
         - dnmonster
         - redis
      network_mode: "bridge"  
 
   dnmonster:
      image: amouat/dnmonster:1.0
      network_mode: "bridge"  

   redis:
      image: redis:3.0
      network_mode: "bridge"  
