version: '2'
services:
   identidock:
      build: .
      expose:
         - "9090"
      environment:
         ENV: PROD
      links:
         - dnmonster
         - redis
      network_mode: "bridge"

   dnmonster:
      image: amouat/dnmonster:1.0
      network_mode: "bridge"      
 
   redis:
      image: redis:3.0
      network_mode: "bridge"
